### ISSUE TITLE
Legend Items Partially Cut Off on Certain Sizes

### ISSUE THREAD

**Issue by deleusec** [ag-grid/ag-charts#1298] opened 2024-03-19 20:46 UTC
**I'm submitting a ...** 
```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

**Providing a Reproducible Scenario**

I've encountered an issue related to the chart legend in AG Charts when used in a Vue.js application with TypeScript. Specifically, on certain sizes, the legend items exceed the boundaries of the chart container and are partially cut off. This problem becomes apparent when resizing the browser window. It can also be observed in the official documentation here: https://charts.ag-grid.com/vue/legend/#size.
![image](https://github.com/ag-grid/ag-charts/assets/59571508/ac8795ca-04cd-4575-bdfa-5dfda5b6ff3a)

**Current behavior**

In specific chart sizes or when the browser window is resized, legend items extend beyond the chart container's bounds, making them partially invisible. This seems to happen without proper detection or adjustment to the chart's container width, leading to a suboptimal user experience as not all legend items are fully visible.

**Expected behavior**

The expected behavior is for the legend items to automatically adjust their layout or the chart container to ensure all legend items are fully visible, regardless of the chart's size or the browser window's dimensions. The legend should dynamically adapt to the available space to maintain accessibility and visibility of all items.

**My environment:**

Operating system: Windows
Browser: Chrome
AG Charts version: 9.1.1
Framework: Vue.js with TypeScript
Language: TypeScript

**Comment by AG-DavidG** [comment] 2024-03-20 09:08
Hello @deleusec 

Thank you for reporting this - much appreciated!
 
Based on your description we've now reproduced this issue as a bug.
 
We have added this bug to our backlog and we are tracking it with the following reference and description:
**AG-11084 - [Charts] Legend items do not always wrap early enough**
 
We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
 
You can get an update on the status of this item on the product pipeline page:
https://charts.ag-grid.com/pipeline/
 
Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Charts. The best way to get an update on this item is to sign up for AG Charts new release notifications. Once a new AG Charts version is released, look for the item reference above (AG-11084) on the changelog page to see if it's resolved in that version:
https://charts.ag-grid.com/changelog/
 
Thanks again for bringing this up with us - we appreciate your time!
 
David‍

**Closed as completed by AG-DavidG** 2024-03-20 09:08 UTC
Labels: AG-11084
