### ISSUE TITLE
AG Charts error DOMException: Node.removeChild: The node to be removed is not a child of this node

### ISSUE THREAD

**Issue by leffle** [ag-grid/ag-charts#1766] opened 2024-06-14 15:08 UTC
**I'm submitting a ...** (check one with "x")

```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Charts team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, our staff will label your issue as managed-by-the-community. This means that AG Grid staff will not be actively looking into it and it will be closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are

-   A description of the detailed steps to reproduce your behaviour in one of our examples in our docs.
-   A Plunker.

If you decide to send us a Plunker, from any example in our website use the Plunker button in there to fork your own code by following the steps below:

-   Select the framework that is appropriate to you from the drop-down
-   Open it in Plunker. (Use the button Plunker in our example)
-   Add your changes so that the behaviour is reproduced
-   Save and Freeze the Plunker (On the top left corner)
-   Send us the link to the Plunker (You can copy the URL from the browser)

If reporting a bug make sure to state:

-   Current behaviour.
-   Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**
On first load of ag-charts-community.js in our app, it works perfectly.

If you reload the page, our Firefox 126.01 running in MacOS 14.5, the console shows this error every reload:

AG Charts error DOMException: Node.removeChild: The node to be removed is not a child of this node
    oldValue https://ebmcalc.com/fhir/lib2/ag-charts-community.js:19604
    ActionOnSet https://ebmcalc.com/fhir/lib2/ag-charts-community.js:9791
    setter https://ebmcalc.com/fhir/lib2/ag-charts-community.js:710
    destroy https://ebmcalc.com/fhir/lib2/ag-charts-community.js:18431
    _Chart2 https://ebmcalc.com/fhir/lib2/ag-charts-community.js:18333
    addListener https://ebmcalc.com/fhir/lib2/ag-charts-community.js:13989
    buildConsumptionHandler https://ebmcalc.com/fhir/lib2/ag-charts-community.js:13890
    dispatchWrapHandlers https://ebmcalc.com/fhir/lib2/ag-charts-community.js:13554
    dispatchTypedConsumable https://ebmcalc.com/fhir/lib2/ag-charts-community.js:13895
    dispatchPointerEvent https://ebmcalc.com/fhir/lib2/ag-charts-community.js:14037
    dispatchEvent https://ebmcalc.com/fhir/lib2/ag-charts-community.js:14011
    __async https://ebmcalc.com/fhir/lib2/ag-charts-community.js:143
    __async https://ebmcalc.com/fhir/lib2/ag-charts-community.js:127
    dispatchEvent https://ebmcalc.com/fhir/lib2/ag-charts-community.js:14009
    processEvent https://ebmcalc.com/fhir/lib2/ag-charts-community.js:14005
    eventHandler https://ebmcalc.com/fhir/lib2/ag-charts-community.js:13949
    _InteractionManager2 https://ebmcalc.com/fhir/lib2/ag-charts-community.js:13971
    ChartContext https://ebmcalc.com/fhir/lib2/ag-charts-community.js:15443
    _Chart2 https://ebmcalc.com/fhir/lib2/ag-charts-community.js:18293
    _CartesianChart2 https://ebmcalc.com/fhir/lib2/ag-charts-community.js:21657
    createChartInstance https://ebmcalc.com/fhir/lib2/ag-charts-community.js:35035
    createOrUpdate https://ebmcalc.com/fhir/lib2/ag-charts-community.js:34941
    create https://ebmcalc.com/fhir/lib2/ag-charts-community.js:34838
    writeGraphs https://ebmcalc.com/fhir/lib2/AHAP.htm:338
    initGraphs https://ebmcalc.com/fhir/lib2/AHAP.htm:348
    <anonymous> https://ebmcalc.com/fhir/lib2/AHAP.htm:2044
ag-charts-community.js:315:15
    error https://ebmcalc.com/fhir/lib2/ag-charts-community.js:315
    errorOnce https://ebmcalc.com/fhir/lib2/ag-charts-community.js:327
    doOnce https://ebmcalc.com/fhir/lib2/ag-charts-community.js:248
    errorOnce https://ebmcalc.com/fhir/lib2/ag-charts-community.js:327
    dispatchWrapHandlers https://ebmcalc.com/fhir/lib2/ag-charts-community.js:13556
    dispatchTypedConsumable https://ebmcalc.com/fhir/lib2/ag-charts-community.js:13895
    dispatchPointerEvent https://ebmcalc.com/fhir/lib2/ag-charts-community.js:14037
    dispatchEvent https://ebmcalc.com/fhir/lib2/ag-charts-community.js:14011
    __async https://ebmcalc.com/fhir/lib2/ag-charts-community.js:143
    __async https://ebmcalc.com/fhir/lib2/ag-charts-community.js:127
    dispatchEvent https://ebmcalc.com/fhir/lib2/ag-charts-community.js:14009
    processEvent https://ebmcalc.com/fhir/lib2/ag-charts-community.js:14005
    eventHandler https://ebmcalc.com/fhir/lib2/ag-charts-community.js:13949
    (Async: EventListener.handleEvent)
    _InteractionManager2 https://ebmcalc.com/fhir/lib2/ag-charts-community.js:13971
    ChartContext https://ebmcalc.com/fhir/lib2/ag-charts-community.js:15443
    _Chart2 https://ebmcalc.com/fhir/lib2/ag-charts-community.js:18293
    _CartesianChart2 https://ebmcalc.com/fhir/lib2/ag-charts-community.js:21657
    createChartInstance https://ebmcalc.com/fhir/lib2/ag-charts-community.js:35035
    createOrUpdate https://ebmcalc.com/fhir/lib2/ag-charts-community.js:34941
    create https://ebmcalc.com/fhir/lib2/ag-charts-community.js:34838
    writeGraphs https://ebmcalc.com/fhir/lib2/AHAP.htm:338
    initGraphs https://ebmcalc.com/fhir/lib2/AHAP.htm:348
    <anonymous> https://ebmcalc.com/fhir/lib2/AHAP.htm:2044

After that the app continues to function and graphs are produced, but I am concerned that the rror may have unexpected consequences in other browsers.

And thank you for your GREAT PRODUCT!

-Louis

**Expected behavior**

No error on page reload

**Please tell us about your environment:**

APache, Firefox 126.01 running in MacOS 14.5

-   **AG Charts version:** 9.0.0

Yes
-   **Browser:**

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:126.0) Gecko/20100101 Firefox/126.0
-   **Language:** [all | TypeScript X.X | ES6/7 | ES5].
- ALL

**Comment by leffle** [comment] 2024-06-15 13:30
Discovered/corrected issue on app side!

Closing issue

**Comment by leffle** [comment] 2024-06-15 20:13
NOPE!  After many reorgs of the code, the exacta same eroor happens on first reload of a page.  Any help/experience appreciated!

**Comment by AG-DavidG** [comment] 2024-06-17 07:27
Hi @leffle 

We'd be happy to look into this for you. 

However we cannot reproduce on our end with the information provided. 

Please provide the following:
1. A live example (plunker, stackblitz, etc) or link to a repo showing the issue
2. A list of steps to follow to reproduce the issue
3. Descriptions of current behavior and expected behavior

Please note that we can only investigate issues that are AG Charts-related and that have been isolated. For instance, if your issue is wrapped in your own logic, we will try to diagnose, but you might find that we come back to you asking for a simplified version of the project showing only the issue in a simpler scenario.

We're looking forward to your response to we can investigate this further.

David

**Comment by AG-DavidG** [comment] 2024-07-10 12:45
Hi @leffle 

As this has been open without any further interaction for a while, I will be closing this issue.

If the issue has already been resolved by other means, you can ignore this. If however, you are still in need of support you can choose to raise the issue again with a reproduction example.

Kind regards,
David

**Closed as completed by AG-DavidG** 2024-07-10 12:45 UTC
Labels: waiting-for-repro
