### ISSUE TITLE
broken package reported while running vitest

### ISSUE THREAD

**Issue by spamshaker** [ag-grid/ag-charts#790] opened 2023-12-28 08:39 UTC
while `vitest run`

SyntaxError: Named export '_Theme' not found. The requested module 'ag-charts-community' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'ag-charts-community';
const { _Theme, } = pkg;

similar issues from the past
https://github.com/ag-grid/ag-grid/issues/4986
https://github.com/ag-grid/ag-grid/issues/6821
https://github.com/vitest-dev/vitest/issues/3688#issuecomment-1612043130

System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.14 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.2/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.13.1 - ~/.nvm/versions/node/v18.18.2/bin/pnpm
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 17.2.1
  npmPackages:
    @ag-grid-community/client-side-row-model: ^31.0.1 => 31.0.1 
    @ag-grid-community/core: ^31.0.1 => 31.0.1 
    @ag-grid-community/react: ^31.0.1 => 31.0.1 
    @ag-grid-community/styles: ^31.0.1 => 31.0.1 
    @ag-grid-enterprise/charts: ^31.0.1 => 31.0.1 
    @ag-grid-enterprise/column-tool-panel: ^31.0.1 => 31.0.1 
    @ag-grid-enterprise/core: ^31.0.1 => 31.0.1 
    @ag-grid-enterprise/menu: ^31.0.1 => 31.0.1 
    @ag-grid-enterprise/rich-select: ^31.0.1 => 31.0.1 
    @ag-grid-enterprise/row-grouping: ^31.0.1 => 31.0.1 
    @vitejs/plugin-react: ^4.2.1 => 4.2.1 
    @vitest/coverage-v8: ^1.1.0 => 1.1.0 
    ag-charts-community: ^9.0.1 => 9.0.1 
    ag-charts-react: ^9.0.1 => 9.0.1 
    vite: ^5.0.10 => 5.0.10 
    vitest: ^1.1.0 => 1.1.0

**Comment by spamshaker** [comment] 2023-12-28 09:02
this actually fails when I am trying to register an enterprise module
```typescript
import { GridChartsModule } from '@ag-grid-enterprise/charts';

ModuleRegistry.registerModules([
  ClientSideRowModelModule,
  RowGroupingModule,
  RichSelectModule,
  MenuModule,
  ColumnsToolPanelModule,
  GridChartsModule // root cause of the issue
]);
```

**Comment by AG-DavidG** [comment] 2024-01-03 14:13
Hello @spamshaker ,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-10212 Vitest fails when registering @ag-grid-enterprise/chart

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can get an update on the status of this item on the product pipeline page:
https://www.ag-grid.com/ag-grid-pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Grid. The best way to get an update on this item is to sign up for AG Grid new release notifications. Once a new AG Grid version is released, look for the item reference above (AG-10212) on the changelog page to see if it's resolved in that version:
https://www.ag-grid.com/ag-grid-changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Closed as completed by AG-DavidG** 2024-01-03 14:13 UTC
Labels: AG-10212
