### ISSUE TITLE
AG chart no scrolling on mobile device possible

### ISSUE THREAD

**Issue by martin1981ww** [ag-grid/ag-charts#1548] opened 2024-05-07 14:49 UTC
**I'm submitting a ...** (check one with "x")

```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Customers of AG Grid**

If you are a customer you are entitled to use the AG Grid's customer support system (powered by Zendesk). Please use that channel for guaranteed response from the AG Charts team with regards bugs, feature requests and support.

**Requesting Community Support**

If you are not a customer of AG Grid, our staff will label your issue as managed-by-the-community. This means that AG Grid staff will not be actively looking into it and it will be closed if inactive for more than one month. The community is welcome to help with this question/support issue.

**Providing a Reproducible Scenario**
Accepted reproducible scenarios are

-   A description of the detailed steps to reproduce your behaviour in one of our examples in our docs.
-   A Plunker.

If you decide to send us a Plunker, from any example in our website use the Plunker button in there to fork your own code by following the steps below:

-   Select the framework that is appropriate to you from the drop-down
-   Open it in Plunker. (Use the button Plunker in our example)
-   Add your changes so that the behaviour is reproduced
-   Save and Freeze the Plunker (On the top left corner)
-   Send us the link to the Plunker (You can copy the URL from the browser)

If reporting a bug make sure to state:

-   Current behaviour.
-   Expected behaviour. If possible back this up with our docs/examples if possible

**Current behavior**

There is no possibility to scroll on mobile devices when pointing the finger over an ag chart.

**Expected behavior**

Scrolling on mobile devices, start with the finger pointing over an ag chart, should be possible

**Please tell us about your environment:**

iPhone 13, iPad (2022)

-   **AG Charts version:** X.X.X

the behaviour also exists on the ag chart website. so my used ag chart version does not matter, I think :-)

-   **Browser:**

Safari

-   **Language:** [all | TypeScript X.X | ES6/7 | ES5]
As used on the ag chart website

**Comment by AG-DavidG** [comment] 2024-05-09 08:09
Hi @martin1981ww 

Can you please provide more information about this scenario, so that we can understand what the problem is.

- Are you trying to scroll the entire page or just the chart?
- Is the entire chart container on the page?
- Are you using the AG Charts zoom feature?

Thanks

David

**Comment by martin1981ww** [comment] 2024-05-14 07:06
Hello @AG-DavidG  and thank you for your patience.

- I'll try to scroll the whole page. When I place my finger over the chart and then try to scroll with a swipe (as usual), it doesn't work.
- The error also occurs here on the page: https://charts.ag-grid.com/gallery/simple-bar/

Can you reproduce it?

**Comment by AG-DavidG** [comment] 2024-05-15 11:44
Hello @martin1981ww ,

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-11622 - Swiping over a chart on a mobile device does not scroll the page

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can get an update on the status of this item on the product pipeline page:
https://charts.ag-grid.com/pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Charts. The best way to get an update on this item is to sign up for AG Charts new release notifications. Once a new AG Charts version is released, look for the item reference above (AG-11622) on the changelog page to see if it's resolved in that version:
https://charts.ag-grid.com/changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Closed as completed by AG-DavidG** 2024-05-15 11:44 UTC
Labels: AG-11622
