### ISSUE TITLE
Property "visible" of AgDonutSeriesOptions not reactive

### ISSUE THREAD

**Issue by M0unir** [ag-grid/ag-charts#1112] opened 2024-02-27 22:00 UTC
**I'm submitting a ...** (check one with "x")

```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Providing a Reproducible Scenario**

**Bug:** Property "visible" of AgDonutSeriesOptions does not update when chart series options change.
**Description:** When trying to update chart series options for a donut chart, the property "visible" does not update. The chart options seem to update correctly but the chart does not react to the series property "visible" and does not update the series visibility. Other properties like "innerRadiusRatio" seem to update correctly. I'm trying to change the chart series visibility based on custom events 

**-   A Plunkr:** [https://plnkr.co/edit/EK0BKNZolLGck1sY?open=index.tsx&preview](https://plnkr.co/edit/EK0BKNZolLGck1sY?open=index.tsx&preview)

**-   Current behavior:** The visible property of AgDonutSeriesOptions does not update when chart series options change.

**-   Expected behavior:**  The chart should update the visibility of donut series when the series options change.

**Please tell us about your environment:**
- Node 18.18.2
- React 18.0.0

-   **AG Charts version:** v9.1.1
-   **Browser:** Google Chrome
-   **Language:** [all | TypeScript X.X | ES6/7 | ES5] Typescript 4.9.5 / ES6+

**Comment by AG-DavidG** [comment] 2024-02-28 13:59
Hello @M0unir 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-10869 - [Charts] Property "visible" of AgDonutSeriesOptions not reactive

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can get an update on the status of this item on the product pipeline page:
https://charts.ag-grid.com/pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Charts. The best way to get an update on this item is to sign up for AG Charts new release notifications. Once a new AG Charts version is released, look for the item reference above (AG-10869) on the changelog page to see if it's resolved in that version:
https://charts.ag-grid.com/changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Closed as completed by AG-DavidG** 2024-02-28 13:59 UTC
Labels: AG-10869
