### ISSUE TITLE
An error occurred when clicking on a legend element while assigning a custom unique identifier to a series.

### ISSUE THREAD

**Issue by bykovmikhail72** [ag-grid/ag-charts#2295] opened 2024-08-22 09:15 UTC
**I'm submitting a ...** (check one with "x")

```
[x] bug report => see 'Providing a Reproducible Scenario'
[] feature request => do not use Github for feature requests, see 'Customers of AG Grid'
[] support request => see 'Requesting Community Support'
```

**Current behavior**

When creating a graph series and assigning a unique identifier to each line, an error occurs when clicking on a legend element.    
Error message: "AG Charts - update error Error: duplicate definition ids on the same scope are not allowed."    
This behavior started after we upgraded to version 10 and has continued to this day.    
Code example:    
```javascript
const series = useMemo(() => Object.entries(data).map(([key, value], index, arr) => {
    const color = customInterpolateColor && customInterpolateColor(index / arr.length)

    return ({
      type: 'line',
      xKey: dateField,
      xName: dateName,
      yKey: yField,
      yName,
      data: value,
      legendItemName: key,
      stroke: color,
      marker: {
        fill: color,
      },
      id: key,
    } as AgLineSeriesOptions | AgBarSeriesOptions | AgAreaSeriesOptions)
  }), [data, dateField, dateName, yField, yName])
```      
I am confident that the key is unique in this case. Additionally, the series of arrays was output to the console, demonstrating that the ID is distinct for each element.    
    
If you don't pass a custom ID, everything works without any problems. However, when I click on a legend element, I cannot distinguish which line was clicked on.

**Expected behavior**

You can pass a custom identifier to the series elements. When you click on the legend, no error is thrown and in the listeners of the legend, you can get the series ID passed when creating the series.    
Series docs: https://charts.ag-grid.com/react/line-series/#reference-AgLineSeriesOptions-id     
Legend docs: https://charts.ag-grid.com/react/legend/#reference-AgChartLegendOptions-listeners-legendItemClick     

**Please tell us about your environment:**    
    
MacOS Sonoma, Visual Studio Code, yarn

-   **AG Charts version:** 10.0.0 -> 10.1.0

-   **Browser:**    
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

-   **Language:** Typescript 5.5.2., React 18.2.0

**Comment by AG-DavidG** [comment] 2024-08-27 08:27
Hello @bykovmikhail72 !

Thank you for reporting this behavior - much appreciated!

We're keen to look into this but we need to be able to reproduce the issue you've described.

Please provide the following (as per our bug template in Github):
1. A live example (plunker, stackblitz, etc) or link to a repo showing the issue
2. A list of steps to follow to reproduce the issue
3. Descriptions of current behavior and expected behavior

We're looking forward to your response to we can investigate this further.

Thank you!

**Comment by bykovmikhail72** [comment] 2024-08-29 13:58
Thank you for your reply. I have prepared an example in Plunker.    
1. https://plnkr.co/edit/e0qAtnaPBCVNSDqz?open=main.ts&preview  - the example. In this example, we can see that when we try to assign a unique identifier to the legend element, clicking on it leads to an error. However, if we remove the ID from the series, we can hide the line without any issues.    
2.  The playback steps: 1. We create a series by assigning a unique identifier to each data point. 2. We enable the navigator and mini chart options. 3. We attempt to click on a legend element to hide a line, but an error occurs. 4. To avoid the error, we temporarily remove the id from the series. 5. After removing the id, everything works as expected.    
3. Waiting description: When you click on a legend element, the line will close and, in the listener for the legend, with the legendItemClick event, we will get the ID set in the series. Reality description: When we click on a legend item, we receive the error - "AG Charts - update error". Error: duplicate definition IDs on the same scope are not allowed.    
    
Screenshot: 
<img width="1504" alt="image" src="https://github.com/user-attachments/assets/403d9c5e-09ed-4d4c-a1a9-32b12cea44fa">     
Also, if an error occurs, the line will not disappear, but if you zoom out in the navigation panel, it may become hidden. However, it will not return when you zoom back in.    
    
    
I am looking forward to receiving a prompt reply. Thank you for your attention.

**Comment by AG-DavidG** [comment] 2024-08-29 15:00
Hi @bykovmikhail72 

Thank you for reporting this - much appreciated!
 
Based on your description we've now reproduced this issue as a bug.
 
We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-12861 - [Charts] Legend toggle throws error when mini chart is enabled and series have user provided ids
 
We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.
 
You can get an update on the status of this item on the product pipeline page:
https://ag-grid.com/charts/pipeline/
 
Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Charts. The best way to get an update on this item is to sign up for AG Charts new release notifications. 
Once a new AG Charts version is released, look for the item reference above (AG-12861) on the changelog page to see if it's resolved in that version:
https://ag-grid.com/charts/changelog/
 
Thanks again for bringing this up with us - we appreciate your time!
 
David

**Closed as completed by AG-DavidG** 2024-08-29 15:00 UTC
Labels: waiting-for-repro, AG-12861
