### ISSUE TITLE
Series line markers disappear when updating chart data

### ISSUE THREAD

**Issue by M0unir** [ag-grid/ag-charts#815] opened 2024-01-05 20:07 UTC
**I'm submitting a ...** (check one with "x")

```
[x] bug report => see 'Providing a Reproducible Scenario'
```

**Providing a Reproducible Scenario**

**Bug:** Series line markers disappear when updating chart data.
**Description:** When trying to update chart data for a line chart with a category axis at the bottom. Some line markers disappear from the line chart. It seems that if the new updated data includes category values that were not present in the previous data set. Then only the new values get line markers while the previous markers get removed.

This seems to happen when the new data precedes the previous data as shown below and in plunker.

![ag charts](https://github.com/ag-grid/ag-charts/assets/2924418/e71895b8-b967-4638-bbd6-277ca2e89efc)

**-   A Plunker:** [https://plnkr.co/edit/OTmHnrDMxqEhNMHT?open=index.jsx](https://plnkr.co/edit/OTmHnrDMxqEhNMHT?open=index.jsx)

**-   Current behaviour:** Some chart line markers disappear after the chart data updates.

**-   Expected behaviour:**  All chart line markers should be displayed after the chart updates.
Would be similar to the behavior shown here in [Real Time Charts](https://charts.ag-grid.com/react/line-series/#real-time-data)
As seen, the chart is updating and line markers are still showing.

**Please tell us about your environment:**
- Node 18.18.2
- React 18.2.0

-   **AG Charts version:** v9.0.1
-   **Browser:** Google Chrome
-   **Language:** [all | TypeScript X.X | ES6/7 | ES5] Typescript 4.9.5 / ES6+

**Comment by M0unir** [comment] 2024-01-05 20:44
Also, when clicking on the legend markers after the data update, the chart will refresh and then show the hidden line markers.

**Comment by AG-DavidG** [comment] 2024-01-07 19:37
Hello @M0unir 

Thank you for reporting this - much appreciated!

Based on your description we've now reproduced this issue as a bug.

We have added this bug to our backlog and we are tracking it with the following reference and description:
AG-10250 - [Charts] Markers disappear when data is updated

We try to fix bugs from one release to the next, so this should be fixed in the next release or the one after if it was raised too close to the next release date.

You can get an update on the status of this item on the product pipeline page:
https://charts.ag-grid.com/pipeline/

Now that this issue is recorded in our backlog, we will soon close the GitHub issue because we will not update it when this bug is fixed in a future version of AG Charts. The best way to get an update on this item is to sign up for AG Chartsnew release notifications. Once a new AG Charts version is released, look for the item reference above (AG-XXXX) on the changelog page to see if it's resolved in that version:
https://charts.ag-grid.com/changelog/

Thanks again for bringing this up with us - we appreciate your time!

**Closed as completed by AG-DavidG** 2024-01-07 19:37 UTC
Labels: AG-10250
